###: defaults
###: see: https://github.com/mojombo/jekyll/wiki/configuration
auto:   true
server: false

#: ++
url:     http://verikami.github.com/ePF_API_doc/
baseurl: http://verikami.github.com/ePF_API_doc/

###: (some) overides
###: see: https://help.github.com/articles/using-jekyll-with-pages#troubleshooting
safe:         true
#source:      .
#destination: ./_site
#lsi:         false
#pygments:    true

###: Jekyll ignores filenames with _*
###: see https://github.com/mojombo/jekyll/issues/324
include: ["_something", "ePF_API_doxy-0.x.x-dev"]
exclude: ["ePF_API", "README.md", "lib", "make", "vendor", "Icon", "make_doc.sh", "package.json"]
